apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-applier
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-applier
  template:
    metadata:
      labels:
        app: kube-applier
    spec:
      serviceAccountName: kube-applier
      containers:
        - name: kube-applier
          image: freemiumvpn/kube-applier:v0.2.0
          imagePullPolicy: Always
          command:
            - "/kube-applier"
          env:
            - name: REPO_PATH
              value: "/git/kubernetes-manifests/prod-gcp"
            - name: LISTEN_PORT
              value: "2020"
            - name: POLL_INTERVAL_SECONDS
              value: "10"
            - name: DIFF_URL_FORMAT
              value: "https://github.com/freemiumvpn/kubernetes-manifests/commit/%s"
            - name: LOG_LEVEL
              value: "1"
          ports:
            - containerPort: 2020
          volumeMounts:
            - name: git-repo
              mountPath: "/git"
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
        - name: git-sync
          image: gcr.io/google_containers/git-sync:v2.0.6
          command:
            - "/git-sync"
          env:
            - name: GIT_SYNC_REPO
              value: https://github.com/freemiumvpn/kubernetes-manifests.git
            - name: GIT_SYNC_BRANCH
              value: main
            - name: GIT_SYNC_DEPTH
              value: "5"
            - name: GIT_SYNC_ROOT
              value: /git
            - name: GIT_SYNC_DEST
              value: kubernetes-manifests
          ports:
            - containerPort: 2020
          volumeMounts:
            - name: git-repo
              mountPath: "/git"
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
      volumes:
        - name: git-repo
          emptyDir: {}
