apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - servive-account.yml
  - cluster-role.yml
  - cluster-role-binding.yml
  - deployment.yml

secretGenerator:
  - name: gcp-key
    namespace: kube-system
    files:
      - secrets/key.json

generatorOptions:
  disableNameSuffixHash: true
