apiVersion: v1
kind: Service
metadata:
  name: &app traefik-ingress-public
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      # nodePort: 30280
    - name: web-secure
      port: 443
      # nodePort: 30243
    - name: traefik
      port: 8080
      # nodePort: 30281
  selector:
    app: *app
