apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog.freemiumpn.com
  namespace: web
spec:
  secretName: blog-fremiumpn-com-ssl
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - blog.freemiumpn.com
