apiVersion: apps/v1
kind: Deployment

metadata:
  name: &app web-auth
  namespace: web
  labels:
    app: *app
    purpose: web

spec:
  selector:
    matchLabels:
      app: *app
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        app: *app
        purpose: vpn
    spec:
      containers:
        - name: *app
          image: freemiumvpn/fpn-auth:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 50Mi
          env:
            - name: LOG_LEVEL
              value: debug
            - name: LOG_OUTPUT
              value: json
            - name: PROMETHEUS_ADDRESS
              value: ":8081"
            - name: CLIENT_ADDRESS
              value: ":8989"
          ports:
            - containerPort: 8081
            - containerPort: 8989
          readinessProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 10
            timeoutSeconds: 2
