apiVersion: v1
kind: Service
metadata:
  name: &service web-auth
  namespace: web
  labels:
    app: *service

spec:
  selector:
    app: *service
  ports:
    - name: *service
      port: 8989
      targetPort: 8989
      protocol: TCP
    - name: metrics
      port: 8081
      targetPort: 8081
      protocol: TCP
