apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
namespace: metrics

resources:
  - deployment.yml
  - service.yml
  - service-account.yml
  - cluster-role.yml
  - cluster-role-binding.yml
