apiVersion: v1
kind: Service
metadata:
  name: &app traefik-ingress-public
  namespace: system
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      nodePort: 30280
    - name: web-secure
      port: 443
      nodePort: 30243
  selector:
    app: *app
