apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:admin-traefik-ingress
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["traefik.containo.us"]
    resources: ["*"]
    verbs: ["*"]
